# Sample .travis.yml for R projects

language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel
warnings_are_errors: true

r_github_packages:
  - jimhester/covr
  - jimhester/lintr



after_success:
  - Rscript -e 'library(covr);codecov()'
  - Rscript -e 'lintr::lint_package()'
